config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :atividades
  resources :eventos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividade.rb
class Atividade < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
  attr_accessor :image
  mount_uploader :image, ImageUploader
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  before_action :set_atividade, only: [:show, :edit, :update, :destroy]

  # GET /atividades
  # GET /atividades.json
  def index
    @atividades = Atividade.all
  end

  # GET /atividades/1
  # GET /atividades/1.json
  def show
  end

  # GET /atividades/new
  def new
    @atividade = Atividade.new
  end

  # GET /atividades/1/edit
  def edit
  end

  # POST /atividades
  # POST /atividades.json
  def create
    @atividade = Atividade.new(atividade_params)

    respond_to do |format|
      if @atividade.save
        format.html { redirect_to @atividade, notice: 'Atividade was successfully created.' }
        format.json { render :show, status: :created, location: @atividade }
      else
        format.html { render :new }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atividades/1
  # PATCH/PUT /atividades/1.json
  def update
    respond_to do |format|
      if @atividade.update(atividade_params)
        format.html { redirect_to @atividade, notice: 'Atividade was successfully updated.' }
        format.json { render :show, status: :ok, location: @atividade }
      else
        format.html { render :edit }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atividades/1
  # DELETE /atividades/1.json
  def destroy
    @atividade.destroy
    respond_to do |format|
      format.html { redirect_to atividades_url, notice: 'Atividade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atividade
      @atividade = Atividade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atividade_params
      params.require(:atividade).permit(:nome, :descricao, :duracao, :palestrante)
    end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :descricao, :local, :data, :horarioInicial, :horarioFinal, :palestrante, :organizador)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :nomeUsuario, :senha)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atividades_helper.rb
module AtividadesHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/atividades/_form.html.erb
<%= form_with(model: atividade, local: true) do |form| %>
  <% if atividade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atividade.errors.count, "error") %> prohibited this atividade from being saved:</h2>

      <ul>
      <% atividade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :duracao %>
    <%= form.text_field :duracao %>
  </div>

  <div class="field">
    <%= form.label :palestrante %>
    <%= form.text_field :palestrante %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/atividades/edit.html.erb
<h1>Editing Atividade</h1>

<%= render 'form', atividade: @atividade %>

<%= link_to 'Show', @atividade %> |
<%= link_to 'Back', atividades_path %>

app/views/atividades/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Atividades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Duracao</th>
      <th>Palestrante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @atividades.each do |atividade| %>
      <tr>
        <td><#%= atividade.nome %></td>
        <td><#%= atividade.descricao %></td>
        <td><#%= atividade.duracao %></td>
        <td><#%= atividade.palestrante %></td>
        <td><#%= link_to 'Show', atividade %></td>
        <td><#%= link_to 'Edit', edit_atividade_path(atividade) %></td>
        <td><#%= link_to 'Destroy', atividade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New Atividade', new_atividade_path %>
-->
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        <div class="list-group">
          <a href="#" class="list-group-item">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item One</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Two</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Three</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Four</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Five</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item Six</a>
                </h4>
                <h5>$24.99</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

app/views/atividades/new.html.erb
<h1>New Atividade</h1>

<%= render 'form', atividade: @atividade %>

<%= link_to 'Back', atividades_path %>

app/views/atividades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @atividade.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @atividade.descricao %>
</p>

<p>
  <strong>Duracao:</strong>
  <%= @atividade.duracao %>
</p>

<p>
  <strong>Palestrante:</strong>
  <%= @atividade.palestrante %>
</p>

<%= link_to 'Edit', edit_atividade_path(@atividade) %> |
<%= link_to 'Back', atividades_path %>

app/views/eventos/_form.html.erb
<%= form_with(model: evento, local: true) do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :horarioInicial %>
    <%= form.text_field :horarioInicial %>
  </div>

  <div class="field">
    <%= form.label :horarioFinal %>
    <%= form.text_field :horarioFinal %>
  </div>

  <div class="field">
    <%= form.label :palestrante %>
    <%= form.text_field :palestrante %>
  </div>

  <div class="field">
    <%= form.label :organizador %>
    <%= form.text_field :organizador %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="container container mt-4 mb-5">
       <h3 class="display-4 text-center"> Eventos </h3>
       <hr class="bg-dark mb-4 w-25">
       <div class="row">
         <% @eventos.each do |evento| %>
           <div class="col-md-4">
               <div class="card">
                   <img class="card-img-top" src="<%= evento.image_url.to_s %>" alt="Card image cap">
                   <div class="card-block p-3">
                       <h4 class="card-title"><%= evento.nome %></h4>
                       <p class="card-text"><%= evento.descricao %></p>
                       <p class="card-text"><%= link_to 'Mostrar mais', evento %></p>
                   </div>
               </div>
           </div>
             <% end %>
          </div>
      </div>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<div class="container mb-5">
    <div class="row">
        <div class="col-md-8">
            <h3 class="display-4"><%= @evento.nome %></h3>
            <hr class="bg-dark w-25 ml-0">
            <p class="lead">
              Local: <%= @evento.local %>
            </p>
            <p>
                <%= @evento.descricao %>
            </p>
            <ul class="list-unstyled pl-4">
                <li><i class="fa fa-check"></i> Data: <%= @evento.data %></li>
                <li><i class="fa fa-check"></i> Horario inicial: <%= @evento.horarioInicial %>. Horario final: <%= @evento.horarioFinal %> </li>
                <li><i class="fa fa-check"></i> Palestrante é o <%= @evento.palestrante %>, organizado por <%= @evento.organizador %> </li>
                <% if current_user.email == @evento.organizador %>
                <li><i class="fa fa-check"></i><td><%= link_to 'Edit', edit_evento_path(@evento) %></td></li>
                <li><i class="fa fa-check"></i><td><%= link_to 'Destroy', @evento, method: :delete, data: { confirm: 'Are you sure?' } %></td></li>
                <%end %>
            </ul>
        </div>
        <div class="col-md-4 mt-5">
          <img class="card-img-top" src=<@evento.image alt="Card image cap">

          <!--<#% if current_user.email == @evento.organizador %> <#%end %><img class="card-img-top" src="<""%= evento.image_url.to_s %>" alt="Card image cap"> -->
        </div>
    </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :nomeUsuario %>
    <%= form.text_field :nomeUsuario %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nomeusuario</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.nomeUsuario %></td>
        <td><%= pessoa.senha %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Nomeusuario:</strong>
  <%= @pessoa.nomeUsuario %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @pessoa.senha %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/welcome/index.html.erb
<h1>UNB Eventos</h1>
<% if user_signed_in? %>
<ul>
  <li><%= link_to "Sair", destroy_user_session_path, method: :DELETE%></li>
</ul>
<%else%>
  <ul>
    <li><%= link_to "Cadastro de novo usuario", new_user_registration_path%></li>
    <li><%= link_to "Logar", new_user_session_path%></li>
  </ul>
<%end %>